# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"USE_64": "01_Pairwise_Distance.ipynb",
         "euclidian_distance_matrix": "01_Pairwise_Distance.ipynb",
         "gpu_dist_matrix": "01_Pairwise_Distance.ipynb",
         "distance_matrix": "01_Pairwise_Distance.ipynb",
         "component_mixture_dist_matrix": "01_Pairwise_Distance.ipynb"}

modules = ["pairwise_distance.py"]

doc_url = "https://Dzeiberg.github.io/dist_curve/"

git_url = "https://github.com/Dzeiberg/dist_curve/tree/master/"

def custom_doc_links(name): return None
