# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://Dzeiberg.github.io/dist_curve/"

git_url = "https://github.com/Dzeiberg/dist_curve/tree/master/"

def custom_doc_links(name): return None
